name: mb_music_picker_example
description: Demonstrates how to use the mb_music_picker plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.5.1
  device_info_plus: ^12.1.0
  mb_music_picker:
    path: ../
  
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
